global using System.Net.Http.Json;
global using Xunit;
global using FluentAssertions;
global using Microsoft.AspNetCore.Mvc.Testing;
global using Microsoft.Extensions.Configuration;
global using Microsoft.Extensions.Hosting;
global using DotNet.Testcontainers.Builders;
global using DotNet.Testcontainers.Containers;
global using DotNet.Testcontainers.Configurations;
